# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: cd gr2201; mvn install -DskipTests; mvn compile; cd fxui;

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080
    onOpen: open-preview

# Docker
image:
  file: .gitpod.Dockerfile